name: TypeScript Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # Ajustez selon vos besoins

    - name: Install dependencies
      run: |
        npm install
        rm -f package-lock.json  # Supprime le fichier lock après l'installation

    - name: Build TypeScript
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist  # Assurez-vous que c'est le bon chemin pour vos fichiers compilés
