name: TypeScript Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Ajustez selon vos besoins

    - name: Check for package-lock.json
      id: check-lock
      run: |
        if [ -f package-lock.json ]; then
          echo "lock_exists=true" >> $GITHUB_OUTPUT
        else
          echo "lock_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Install dependencies (with lock)
      if: steps.check-lock.outputs.lock_exists == 'true'
      run: npm ci

    - name: Install dependencies (without lock)
      if: steps.check-lock.outputs.lock_exists == 'false'
      run: |
        npm install
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add package-lock.json
        git commit -m "Add package-lock.json" || echo "No changes to commit"

    - name: Build TypeScript
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist  # Assurez-vous que c'est le bon chemin pour vos fichiers compilés
